//mypages.js 
//2023-03-01: by jcr 

exports.genMainPage=function(lista,data){
    var pagHTML=`
            <!DOCTYPE html>
            <head>
                <meta charset= "UTF-8"/>
                <title> About people...</title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
                <div class="w3-card-4">

                <header class="w3-container w3-blue">
                <h1>Lista de Pessoas na Base de Dados(${lista.length})</h1>
                </header>
                
            <div class="w3-container">
                <table class="w3-table-all">
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Idade</th>
                    <th>Sexo</th>
                    <th>Cidade</th>
                </tr>`
    for(let i=0;i<lista.length;i++){
        pagHTML +=`
        <tr>
                <td>${lista[i].id}</td>
                <td>
                    <a href="http://localhost:7777/pessoas/${lista[i].id}">
                    ${lista[i].nome}
                    </a>
                </td>
                <td>${lista[i].idade}</td>
                <td>${lista[i].sexo}</td>
                <td>${lista[i].morada.cidade}</td>
           
        </tr>
        
        
        `
    }
    pagHTML+=`
                </table>
            </div>
            
            <footer class="w3-container w3-blue">
              <h5>Generated by pessoas-server:${data}</h5>
            </footer>
            
            </div>
                
            </body>
        </html>
    `
    return pagHTML
}
//mypages.js 
//2023-03-01: by jcr 

exports.pessoaPage=function(pessoa,data){
    var pagHTML=`
            <!DOCTYPE html>
            <head>
                <meta charset= "UTF-8"/>
                <title> About people...</title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
                <div class="w3-card-4">

                <header class="w3-container w3-blue">
                <h1>${pessoa.nome}</h1>
                </header>
                
            <div class="w3-container">
            `
   
    pagHTML+=`
                </table>
            </div>
            
            <footer class="w3-container w3-blue">
              <h5>Generated by pessoas-server:${data}</h5>
            </footer>
            
            </div>
                
            </body>
        </html>
    `
    return pagHTML
}

exports.genSexoPage=function(mulheres,homens,d){
    var pagHTML=`
            <!DOCTYPE html>
            <head>
                <meta charset= "UTF-8"/>
                <title> About people...</title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
                <div class="w3-card-4">

                <header class="w3-container w3-blue">
                <h1>Homens(${homens.length})</h1>
                </header>
                
            <div class="w3-container">
                <table class="w3-table-all">
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Idade</th>
                    <th>Cidade</th>
                </tr>`
    for(let i=0;i<homens.length;i++){
        pagHTML +=`
                <tr>
                        <td>${homens[i].id}</td>
                        <td>
                            
                            ${homens[i].nome}
                        </td>
                        <td>${homens[i].idade}</td>
                        <td>${homens[i].sexo}</td>
                        <td>${homens[i].morada.cidade}</td>
                
                </tr>
        
        `
    }
    pagHTML += `
            </table>
        </div>
    `
    pagHTML +=`
            <div class="w3-card-4">

                <header class="w3-container w3-blue">
                <h1>Mulheres(${mulheres.length})</h1>
                </header>
                
            <div class="w3-container">
                <table class="w3-table-all">
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Idade</th>
                    <th>Sexo</th>
                    <th>Cidade</th>
                </tr>

    `
    for(let i=0;i<mulheres.length;i++){
        pagHTML +=`
                <tr>
                        <td>${mulheres[i].id}</td>
                        <td>
                            
                            ${mulheres[i].nome}
                        </td>
                        <td>${mulheres[i].idade}</td>
                        <td>${mulheres[i].sexo}</td>
                        <td>${mulheres[i].morada.cidade}</td>
                
                </tr>     
        `
    }
    pagHTML += `
            </table>
        </div>
        `
    pagHTML+=`
            
            <footer class="w3-container w3-blue">
              <h5>Generated by pessoas-server:${d}</h5>
            </footer>
            
            </div>
                
            </body>
        </html>
    `
    return pagHTML
}

exports.genDesportoPage=function(desportistas,d){
    var pagHTML=`
            <!DOCTYPE html>
            <head>
                <meta charset= "UTF-8"/>
                <title> About people...</title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
        `
    desportistas.forEach (function(value, key) {
        pagHTML +=`
            <div class="w3-card-4">

            <header class="w3-container w3-blue">
            <h1>${key}(${value.length})</h1>
            </header>
            <div class="w3-container">
            <table class="w3-table-all">
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Idade</th>
                <th>Sexo</th>
                <th>Cidade</th>
            </tr>
            `
            for(let i=0;i<value.length;i++){
                pagHTML +=`
                        <tr>
                                <td>${value[i].id}</td>
                                <td>
                                    
                                    ${value[i].nome}
                                </td>
                                <td>${value[i].idade}</td>
                                <td>${value[i].sexo}</td>
                                <td>${value[i].morada.cidade}</td>
                        
                        </tr>
                
                `
            }
            pagHTML += `
                    </table>
                </div>
                `
    })
    
    pagHTML+=`
            
            <footer class="w3-container w3-blue">
              <h5>Generated by pessoas-server:${d}</h5>
            </footer>
            
            </div>
                
            </body>
        </html>
    `
    return pagHTML
}

exports.genProfissaoPage=function(profissoes,d){
    var top = 1;
    var pagHTML=`
            <!DOCTYPE html>
            <head>
                <meta charset= "UTF-8"/>
                <title> About people...</title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
        `
    profissoes.forEach (function(value, key) {
        if (top <=10){
            pagHTML +=`
                <div class="w3-card-4">

                <header class="w3-container w3-blue">
                <h1>${key}</h1>
                </header>
                <div class="w3-container">
                <table class="w3-table-all">
                <tr>
                    <th>Frequência</th>                 
                </tr>
                `
                pagHTML +=`
                <tr>
                        <td>
                            <a href="http://localhost:7777/profissao/${key}">
                            ${value.length}
                            </a>
                        </td>
                </tr>
                            `
                
                pagHTML += `
                        </table>
                    </div>
                    `
                top++;
        }
        
    })
    
    pagHTML+=`
            
            <footer class="w3-container w3-blue">
              <h5>Generated by pessoas-server:${d}</h5>
            </footer>
            
            </div>
                
            </body>
        </html>
    `
    return pagHTML
}
exports.pessoasPage=function(lista,data){
    var pagHTML=`
            <!DOCTYPE html>
            <head>
                <meta charset= "UTF-8"/>
                <title> About people...</title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
                <div class="w3-card-4">

                <header class="w3-container w3-blue">
                <h1>Pessoas que exercem a profissão(${lista.length})</h1>
                </header>
                
            <div class="w3-container">
                <table class="w3-table-all">
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Idade</th>
                    <th>Sexo</th>
                    <th>Cidade</th>
                </tr>`
    for(let i=0;i<lista.length;i++){
        pagHTML +=`
        <tr>
                <td>${lista[i].id}</td>
                <td>${lista[i].nome}</td>
                <td>${lista[i].idade}</td>
                <td>${lista[i].sexo}</td>
                <td>${lista[i].morada.cidade}</td>
           
        </tr>
        `
    }
    pagHTML+=`
                </table>
            </div>
            
            <footer class="w3-container w3-blue">
              <h5>Generated by pessoas-server:${data}</h5>
            </footer>
            
            </div>
                
            </body>
        </html>
    `
    return pagHTML
}
