exports.usersTasksListPage = function(users,tasks,d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Task Manager</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>User List</h1>
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < users.length ; i++){
        pagHTML += `
                <tr>
                    <td>${users[i].id}</td>
                    <td>${users[i].nome}</td>
                    <td>[<a href="/users/edit/${users[i].id}">Edit</a>][<a href="#">Delete</a>]</td>
                </tr>
        `
    }
    pagHTML += `
            </table>
            </div>
            `
    pagHTML += `
            <header class="w3-container w3-teal">
                <h1>Task List</h1>
            </header>

            <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                    <th>Deadline</th><th>Who</th><th>What</th>
                    <th>Actions</th>
                </tr>
    `
    for(let i=0; i < tasks.length ; i++){
        pagHTML += `
                <tr>
                    <td>${tasks[i].deadline}</td>
                    <td>${tasks[i].who}</td>
                    <td>${tasks[i].what}</td>
                    <td>[<a href="#">Edit</a>][<a href="#">Delete</a>]</td>
                </tr>
        `
    }
    pagHTML += `
            </table>
            </div>
    `
    pagHTML += `
                <footer class="w3-container w3-teal">
                    <h5>Generated by Gonçalo Braga in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}
exports.userFormEditPage = function(u,d){
    var pagHTML= `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student edit form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>MetaData</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${u.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${u.nome}"/>
                    </fieldset>

            `

    pagHTML+=    ` 
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by Gonçalo Braga in ${d} - [<a href="/users">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML;
}